Update to NuGet 2.6
Microsoft Xml Document Transformations (XDT) are not working in Mono 2.10.9:

System.IO.InvalidDataException: An error occurred while applying transformation to 'app.config' in project 'NuGetTest': Argument cannot be null.
Parameter name: key ---> Microsoft.Web.XmlTransform.XmlNodeException: Argument cannot be null.
Parameter name: key ---> System.ArgumentNullException: Argument cannot be null.
Parameter name: key
  at System.Xml.NameTable.Add (System.String key) [0x000ae] in /home/abuild/rpmbuild/BUILD/mono-2.10.9/mcs/class/System.XML/System.Xml/NameTable.cs:111
  at System.Xml.XmlAttribute.set_Prefix (System.String value) [0x0004b] in /home/abuild/rpmbuild/BUILD/mono-2.10.9/mcs/class/System.XML/System.Xml/XmlAttribute.cs:210
  at Microsoft.Web.XmlTransform.XmlElementContext.ScrubTransformAttributesAndNamespaces (System.Xml.XmlNode node)
  at Microsoft.Web.XmlTransform.XmlElementContext.CreateCloneInTargetDocument (System.Xml.XmlNode sourceNode)
  at Microsoft.Web.XmlTransform.XmlElementContext.get_TransformNode ()
  at Microsoft.Web.XmlTransform.Transform.get_TransformNode ()
  at Microsoft.Web.XmlTransform.Transform.ApplyOnAllTargetNodes ()
  at Microsoft.Web.XmlTransform.Transform.Execute (Microsoft.Web.XmlTransform.XmlElementContext context, System.String argumentString)